import base64, subprocess, os, sys
# Unicode coverage: Latin + punctuation + arrows + geometric shapes + checks
UNI = "U+0020-007E,U+00A0-00FF,U+2010-2027,U+2030-205E,U+20AC,U+2190-2199,U+2200-22FF,U+25A0-25FF,U+2713-2717,U+27F3,U+2026,U+2192"
faces = [
  ("NimbusSans-Regular", "/usr/share/fonts/opentype/urw-base35/NimbusSans-Regular.otf", "Obol Sans", 400, "normal"),
  ("NimbusSans-Bold",    "/usr/share/fonts/opentype/urw-base35/NimbusSans-Bold.otf",    "Obol Sans", 700, "normal"),
  ("NotoSansMono-Regular","/usr/share/fonts/truetype/noto/NotoSansMono-Regular.ttf",    "Obol Mono", 400, "normal"),
  ("NotoSansMono-Bold",   "/usr/share/fonts/truetype/noto/NotoSansMono-Bold.ttf",       "Obol Mono", 700, "normal"),
]
css = []
total = 0
for name, src, fam, weight, style in faces:
    out = f".fonttmp/{name}.woff2"
    subprocess.run(["pyftsubset", src, f"--unicodes={UNI}", "--flavor=woff2",
                    "--layout-features=kern,liga,calt,tnum,zero",
                    f"--output-file={out}", "--no-hinting", "--desubroutinize"], check=True)
    b = open(out,"rb").read()
    total += len(b)
    b64 = base64.b64encode(b).decode()
    css.append(f"@font-face{{font-family:'{fam}';font-style:{style};font-weight:{weight};font-display:swap;src:url(data:font/woff2;base64,{b64}) format('woff2');}}")
    print(f"{name}: {len(b)//1024}KB", file=sys.stderr)
print(f"TOTAL embedded: {total//1024}KB", file=sys.stderr)
open("editor/fonts.js","w").write("// Auto-generated by scripts/build-fonts. Offline-embedded subsets (Nimbus Sans + Noto Sans Mono).\nmodule.exports = " + repr("".join(css)) + ";\n")
